### PR TITLE
SCSN: Bill of material

### PR DESCRIPTION
**Pull request by alberthoekstra**
Generator added for the bill of material file.
Website: https://smartconnected.semantic-treehouse.nl/

Having some problems with lines in XSD that reference to CBC types.
See lines; 40, 44 and 132.
@remcoros any idea how to fix this?

### CODE REVIEW

**Comment by remcoros** [comment]
I never tested the generator with a new UBL 'maindoc' document (root type), only with Extension types (like the SEeF extension).

It seems more things are going wrong when used this way:

It inherits from BaseDocument, but does not explicitly implement IBaseDocument like the other main types. (you get the warning about "ID" property hiding its base property).
This is because the generator has somewhat hardcoded that document types come from an url (path) with "maindoc" in it.
This works in conjunction with BaseDocument-2.1.xsd (which is not an actual UBL document, but a hack to make inheritance work in c#). Since that BaseDocument.xsd is not available when parsing the SCSN schema, things go wrong.

A quick work-around would be to place the SCSN schema in the "maindoc" dir and use the main generator (the one for UblSharp types). and manually cut/paste the files to SCSN project.

A real solution would be to refactor the generator a bit so it can handle "3rd party maindocs", but that's gonna take some time.

I just tried it and seems to work, just replace the imports with:

```
    <xsd:import namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
                schemaLocation="../common/UBL-CommonAggregateComponents-2.1.xsd"/>
    <xsd:import namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
                schemaLocation="../common/UBL-CommonBasicComponents-2.1.xsd"/>
    <xsd:import namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
                schemaLocation="../common/UBL-CommonExtensionComponents-2.1.xsd"/>
```

**Comment by alberthoekstra** [comment]
Okay so I've tried what you suggested.
When I run the 'UblSharp.Generator' the same exception occures.
```
System.Xml.Schema.XmlSchemaException: 'Het type urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2:IDType is niet gedeclareerd.'
System.Xml.Schema.XmlSchemaException
  HResult=0x80131941
  Message=Het type urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2:IDType is niet gedeclareerd.
  Source=System.Xml
  StackTrace:
   at System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.BaseProcessor.SendValidationEvent(XmlSchemaException e, XmlSeverityType severity)
   at System.Xml.Schema.Compiler.CompileElement(XmlSchemaElement xe)
   at System.Xml.Schema.Compiler.CompileParticleElements(XmlSchemaComplexType complexType, XmlSchemaParticle particle)
   at System.Xml.Schema.Compiler.CompileParticleElements(XmlSchemaComplexType complexType, XmlSchemaParticle particle)
   at System.Xml.Schema.Compiler.CompileComplexTypeElements(XmlSchemaComplexType complexType)
   at System.Xml.Schema.Compiler.Compile()
   at System.Xml.Schema.Compiler.Execute(XmlSchemaSet schemaSet, SchemaInfo schemaCompiledInfo)
   at System.Xml.Schema.XmlSchemaSet.Compile()
   at UblSharp.Generator.UblGenerator.Generate(UblGeneratorOptions options) in C:\Projects\UblSharp\src\UblSharp.Generator.Core\UblGenerator.cs:line 110
   at UblSharp.Generator.Program.Main(String[] args) in C:\Projects\UblSharp\src\UblSharp.Generator\Program.cs:line 12

  This exception was originally thrown at this call stack:
	System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(object, System.Xml.Schema.ValidationEventArgs)
	System.Xml.Schema.BaseProcessor.SendValidationEvent(System.Xml.Schema.XmlSchemaException, System.Xml.Schema.XmlSeverityType)
	System.Xml.Schema.Compiler.CompileElement(System.Xml.Schema.XmlSchemaElement)
	System.Xml.Schema.Compiler.CompileParticleElements(System.Xml.Schema.XmlSchemaComplexType, System.Xml.Schema.XmlSchemaParticle)
	System.Xml.Schema.Compiler.CompileParticleElements(System.Xml.Schema.XmlSchemaComplexType, System.Xml.Schema.XmlSchemaParticle)
	System.Xml.Schema.Compiler.CompileComplexTypeElements(System.Xml.Schema.XmlSchemaComplexType)
	System.Xml.Schema.Compiler.Compile()
	System.Xml.Schema.Compiler.Execute(System.Xml.Schema.XmlSchemaSet, System.Xml.Schema.SchemaInfo)
	System.Xml.Schema.XmlSchemaSet.Compile()
    UblSharp.Generator.UblGenerator.Generate(UblSharp.Generator.UblGeneratorOptions) in UblGenerator.cs
    ...
    [Call Stack Truncated]
```

**Comment by remcoros** [comment]
Just pushed a new branch SCSN on this repo, I think you have push permissions, should have the fixes :) you can continue from there, also fixed the CI build.ps1, new projects need an entry there.

**Comment by remcoros** [comment]
@alberthoekstra Closing this in favor of the branch: https://github.com/UblSharp/UblSharp/tree/SCSN

Can you check if that's what you need? I think everything works. also added the OrderStatus and TPDPackage xsd's.

If you can check/test if this is what you need, make any changes if needed, then send a new PR from that branch, I can make a release to nuget.

**Pull request closed without merging**
