### PR TITLE
Added support for SEeF V3.

### PR DESCRIPTION
**Pull request by fvandillen**
~Added support for SEeF 2.1 by using the existing 2.0 code.~

Added support SEeF 3.0 by generating a new extension class based on the XSD 3.0 (included in the project).

### CODE REVIEW

**Comment by fvandillen** [comment]
I don't have a sample XML for 3.0 yet, will try and add a unit test ASAP.

**Comment by remcoros** [comment]
Looks good, if you can change the enum as I commented and move back V1 to the main namespace (to not break existing code), I will do a quick test and merge / release.

**Comment by fvandillen** [comment]
This is going to take a little more time than expected. I've been in touch with the folks from Energie e-Factuur to get the 2.1 spec, and it turns out there is none. The reason I built the 2.1 code is because of the supplier De Groene Stroomfabriek who defined the seef namespace with version 2.1 where they should have used 2.0. I've contacted the people over at the supplier and asked them to fix this. Will remove the 2.1 code from this PR.

**Comment by remcoros** [comment]
@fvandillen what should I do with this? Was there a 2.1 and/or 3.0 spec and should we add that. Or just close this PR?

**Comment by fvandillen** [comment]
I actually looked at this PR today. Never gotten around to finishing it. Since we are actively using the library in our environment and also have a need for 3.0, I will make sure this gets done ASAP. Give me a few days :)

Met vriendelijke groet,

Florian van Dillen
________________________________

**Comment by jerone** [comment]
@remcoros SEeF 2.1 is now removed, because it does not exists. An example xml for 3.0 and tests are now also included.

Please note that this is probably a breaking change, as it requires the user to use the correct version namespace.

**Comment by remcoros** [comment]
Yea, the V1 and V2 schema are identical except for the namespace. Didn't look closely, but I suppose V3 has a different schema (hence the need for a new type).

It's not really breaking for users of V1 and V2. But in case they want to support V3, it needs some additional work of the user to determine which serializer to use (inspecting the namespace of the source document or something and then use the correct type).

I don't have hands-on experience using these (I'm not in the energy market), so I'll leave that up to the users and maybe a future contribution.

I'll review / test it asap.

**Comment by remcoros** [comment]
Thanks a @fvandillen @jerone When release build passes, I'll tag it and it should publish a new nuget package (1.2.0 for SEeF)

**Pull request merged**
